modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="epicparagliders"
version="${file.jarVersion}"
displayName="Epic Paragliders Mod"
logoFile="epicparagliders.png"
credits="Thanks for this example mod goes to Java"
authors="CravenCraft"
description='''
A mod that is meant to be a compat between the Epic Fight mod and the Paragliders mod. It will override the Epic Fight
stamina system, and use the one from Paragliders instead.
'''
[[dependencies.epicparagliders]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicparagliders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
